# Dependencies
markdown:         kramdown
rouge:            true

# Permalinks
permalink:        pretty

# Setup
title:            My Blogs
tagline:          '0712'
description:      'Made by <a href="https://twitter.com/vovansinh" target="_blank">@SinhVV</a>.'
url:              http://google.com

author:
  name:           'SinhVV'
  url:            https://github.com/vovansinh

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/vovansinh
